# Generated by Django 3.2.5 on 2021-07-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
