# Generated by Django 3.2.5 on 2021-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_thumbnail_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Header picture', null=True, upload_to='images/', verbose_name='Header picture'),
        ),
    ]
